# Generated by Django 4.0.2 on 2022-02-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('num_bikes', models.SmallIntegerField(default=0)),
                ('bikes_available', models.SmallIntegerField(default=0)),
                ('docks_available', models.SmallIntegerField(default=0)),
                ('capacity', models.SmallIntegerField(default=0)),
                ('is_renting', models.BooleanField()),
                ('is_installed', models.BooleanField()),
                ('is_returning', models.BooleanField()),
                ('arrondissement', models.CharField(max_length=30)),
            ],
        ),
    ]
